package lesson4;

import java.util.Scanner;

public class Dustbin {
    public static void main(String[] args) {
        int credit = 0;
        boolean flag = true;
        Machine m1 = new Machine();

        while (flag) {
            System.out.println("Please, type your command (insert money  [F] or make a foto [M]");
            Scanner in = new Scanner(System.in);
            String command = in.nextLine();


            switch (command) {
                case "SystemInfo":
                    printInfo(in);
                    break;
                case "F":
                    if (credit >= 10) {
                        System.out.println("Smile!:)");
                        credit -= 10;
                        printFoto();
                    } else {
                        System.out.println("Err[02]: Not enough money");
                    }
                    break;
                case "M":
                    insertBanknotes(m1, in);
                    credit += m1.countPapers();
                    break;

                case "Q":
                    System.out.println("Goodbye my lover, goodbye my friend");
                    flag = false;
                    //System.exit(0);
                    break;

                default:
                    System.out.println("Err[01]: Invalid command");
            }
        }
    }

//Case methods

    public static void printFoto() {
        System.out.println("MMMWWWWMMMMWNWWMMMWWNWWMMWWWWWMMMWWNWWMMMWWNWWMMMWNWWMMMWNNWMMMWWNWWMMMWNWWMMMWWNWWMMMMWWNWWMMWWNWWMMMWWNWWMMWWWWWMMMWWNWWMMMWWWWMMMWWWWWMMMWWNWWMMMWNWWMMMWWNWWMMMWNNWMMM\n" +
                "WWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "NNWWMMMWWWWMMMWWNWWMMWWWWWWMMWWNWWMMMWWWWWMMWWWWWMMMWWWWWMMMWWWWMMMWWWWWMMWWWWWWMMWWWWWWMMMWWNWMMMWWWWWMMMWWWWWMMWWWWWMMWWWWWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMMWWNWWMMWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "MMWWWWWWMMWWNWWMMMWWWWWMMWWNWWMMMWWNWWMMMWNNWWMMWWNWWMMMWWWWMMMWWNWWMMMWNNWMMMWWNWWMMMMWWNWWMMWWWWWMMMWWNWWMMWWWWWMMMWWWWWMMMWWWWMMMWWWWWMMMWWNWWMMMWNNWMMMWWNWWMMMWWWWMMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WNWWMMWWWWWMMMWWNWWMMWWNNWMMMWWWWWMMMWNNWMMMWWWWWMMMWWNWWMMWWNWWMMMWWNWWMMMWNWWMMMWWWWWWMMWWNNWMMMWWWWWMMMWWWWWMMWWNNWMMMWWNWWMMWWNNWMMMWWWWWMMWWWWWMMMWWNWWMMMWNNWWMMWWWW\n" +
                "WWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWM\n" +
                "MMMWWWWMMMWWNNWMMMWWNWWMMWWWWWMMMWWWWWMMMWWNWWMMMWNWWMMWWWWWMMMWWNWWMMMWNNWMMMWWNWWMMMWWWNWWMMWWWWWWMMWWNWWMMMWWWWMMMWWNWWMMMWWWWMMMWNNWWMMMWWWWWMMWWNWWMMMWWNWWMMWWWWWMMM\n" +
                "WWWWWWMWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWMMMWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWNXK000000XNNWWWWWWWWWWWWMWWWWWWWMWWWWWWWWWWWWWMMWWWWWWMWWWWWWMMWWWWWWWWWWWWWMWWWWWWWWWWWW\n" +
                "WWWWMMWWWWWMMWWWNWWMMWWWNWWMMWWWWWMMWWWWWWMMMWWWWMMMWWWWWMMWWWWWMMWWWWWWWNKOkdl:;,........',,;lxOKNWWWWWMMWWWWWMMWWWWWMMMWWNWWMMWWWWWMMMWWWWWMMWWWWWWMMWWWWWMMMWWWWMMMWWWW\n" +
                "WMMWWWWWMMWWWWWWMWWWWWWMMWWWWWWMMWWWWWWMWWWWWWWMWWWWWMMWWWWWWMWWWWWNKkdl:'...     ......        ..,lxKWWWWWWWWWWWWWMMWWWWWWMWWWWWWMMWWWWWWMMWWWWWMWWWWWWWMWWWWWWWMWWWWWWMM\n" +
                "MMWWWWWWMMWWWWWWMMWWWWWMMWWWWWMMMWWWWWMMMWWWWWMMWWWWWMMWWWWWWWWW0dc,.            .. .....  ...      ..cx0NWWMMWWWWWMMWWNWWMMWWWWWWMMWWWWWMMWWWWWWMMWWWWWWMMWWWWWMMWWWWWWMM\n" +
                "WWWWMMWWNWWMMMWWWWWMMWWWWWWMMWWWWWMMMWWWWWMMWWWWWWMMWWWWWWMWN0d;.                ....................  ..;dKNWWWMWWNWWMMMWWWWMMMWWWWWMMMWWWWWMMWWWWWWMMWWWWWWMMWWWWWMMWWWW\n" +
                "WWWWMMMWWWWMMMWWWWWMMWWWWWWMMWWWWWMMMWWWWWMMMWWWWMMMWWWWWWXd;.                ........................... ..lKWWWWWWWWMMMWWWWWMWWWWWWMMMWWWWWMMWWWWWWMWWWWWWMMMWWWWMMMWWWW\n" +
                "MMWWWWWWMMWWWWWMMMWWNWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWMMWKo'                .................'''..............'kNWWMMMWWWWWMMMWWNWMMMWWWWWMMMWWWWWMMWWNWWMMMWWWWWMMMWWWWMMM\n" +
                "WMMWWWWWMWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWMMWWWWWWKo.          .. .............'',,,;;:clollllccccc::;'....lXWWWMWWWWWWWWWWWWWMWWWWWWMMWWWWWWMMWWWWWMWMWWWWWMWWWWWWWWW\n" +
                "NWWWMMMWWWWMMMWWNWWMMMWWWWWMMWWWWWMMMWWNWWMMWWWWWWWMKl'.    . ..  ........'',;:ccclooddxxxxkkkkkxxxxxxxxxxdlc:,':ONNNWMMMWWNWWMMMWNNWMMMWWWWWMMWWWWWWMMWWNWWMMMWWNWWMMWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,       ........'',;:clloooddddxxxxxxkkkkkkkkkkkkkOOOkkxdol:''dNWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "MMMWWWWWMMWWNWWMMMWWWWWMMWWWWWMMMWWNWWMMMWNNWMMMWNo.       ......',;cllooooooddddxxxxxxxxkkkkkkkkkkOOOOOOOkkxxxoc'.oNWWWWWMMMWNNWMMMWWNWWMMMWWWWWMMMWNWWMMMWWNWWMMMWNNWMMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx.      ....,;;:ccclooooooddddddddxxxxxxxxxxkkkkkkkkOOkkkxxxxxxdl..xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWMMMWNNWMMMWWNWMMMMWWWWMMMWWNWWMMMWWNWWMMWWWW0'      ....;:ccccclllllloooddddddddddxxxxxxxxxxkkkkkkkkkxxxxxxxxd:.,0MMMWWNWWMMWWWWWMMMWWNWWMMWWWWWWMMWWWWWMMMWNNWWMMWWNW\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWo      ....';::cc:cccccllllooodddddddddxxxxxxxxxxxkkkkkkkkkxxxdddxo'.dWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "MMMWWWWWMMMWNWWMMMWWWWWMMWWWWWMMMWWWWWMMMWWWWMMX:       ....;:::::cccccllllooodddddddxxxxxxxxxxxxxkkkkkkkkkxxxddddo;.:XWWWMMWWWWWWMMWWWWWMMMWWNWWMMMWWWWMMMWWNWWMMMWWWWMMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX;       ....,;::::::ccclllloooooddddxxxxkkkkxxxxxkkkkkkkkkkxxddoodo:.;0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWMMMWNNWMMMWWNWWMMMWWWWMMMWWNWWMMMWWWWWMMWWWX;        ...';;;;;;::::cllllooodddddxxxxxkkkkkxxxxxxxxxxxkkxxxxdddol''kMWWNNWWMMWWNWWMMMWWNWWMMMWWWWMMMWWNWWMMMWWNWWMMWWNN\n" +
                "WMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWMX;       .....,;;;;;;;;::cclloooodddddddddxxxxxxxxxddoolcc::::clooooo;.xWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "MMMWWWWWMMWWNWWMMMWWWWMMMWWWWWMMWWWWWWMMMWWWWWMX;       .....,,,,,;;;::ccllcccccccclllloooooooooooolc;'........'',;c;'oNWWMMMWWWWMMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWWMM\n" +
                "WWWWWWWWWWWWMWWWWWWWMWWWWWWMMWWWWWWWWWWWWWMMWWWNl       .....,,,,;;:ccc:;,'........';:ccccllllccccc:,.................oNWWWWWWWMMWWWWWMMWWWWWWWWWWWWWMWWWWWWWMWWWWWWMMWWWW\n" +
                "WWWWMMWWWWWMMMWWWWWMMMWWWWMMMWWWWWMMMWWWWWMMWWNWk.     .....',,,,;::;,'...      .....',;;:clllllc:;,'..........'',;,'.lXWWWNWWMMWWWWWMMMWWWWWMMWWWWWWMMWWNWWMMMWWWWWMMWWWW\n" +
                "MMMWWWWWMMWWWWWMMWWWWWWMWWWWWWMMWWWWWWMMWWWWWWMW0,     ....',,,,,;,'...................',;clodxxdl;,'.....      ...,::lKWWWMWWWWWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWMMM\n" +
                "MMMWWWWWMMWWWWWMMMWWWWWMMWWWWWWMMWWWWWMMMWWWWMMWNc     ....',,,,,....''''....     ......';lodxkkkxl:;,,''',,;:::;,'';:lxOOXWMWWWWMMMWWWWWMMMWWWWWMMWWWWWMMWWWWWWMMWWWWWWMM\n" +
                "WWWWMMMWWWWMMMWWNWWMMMWWWWWMMMWWWWMMMWWWWWMMWWWNWx.    ....,,,,,'..','..   ...........',;:codxkkOkxdolc:;;;;;::ccllodoollcoKWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMMWWNWWMMWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWMMWWWWWWMMWWWWWWMWWWWWWMWWWWWWO.    ....,;;,''','....'',;;;;;;;;;:::cccclodxxkkkxxxxdooolloooddxkkxdo:'cKWWMWWWWWWWWWWWWWWMMWWWWWWMMWWWWWMMWWWWWWMMWWWW\n" +
                "MMWWWWWMMMMWNWWMMWWWWWWMMWWWWWWMMWWWWWMMMWWWWWMWWXc   .....,;;,''''',;;;;;;;;;;::clloolcc:cloddxkkkkxxxxxxxdxxxxxkkOkkdol;c0WWNWWWMMWWWWWMMMWNWWMMMWWWWWMMMWWNWWMMWWWWWWMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWMWWWWWWWKkxl...  ...,,,,,,,;:cclooooooooddoooollccccllodxkkkkkxxxxdllloxxxkOOkkxdocl0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMM\n" +
                "WNWWMMMWNNWMMMWWNWWMMMWWNWMMMMWWWWMMMWWWWWMWWNk;'',,,'.....',,,,,;::ccoodddxddxxdollllcc:cclloddxkkkkkkkxdc:::loodxkkkxdoloKWWMWWWNNWMMMWWNNWMMWWWWWMMMWWNWWMMMWNNWWMMWWNN\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc......',,...',,,,;;:::loddddddodolc::cclllcclllodxkkOkxxxkdc:;,,:clodxxxdolxNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "MMMWWWWWMMMWNWWMMMWWWWWMMMWNNWMMMWWWWWMMMWNNWXc......''''...,,,;;;;:cloolooooll:;;,,;:cllc:;:cloooddl:;:llccc:,'';:cloddolkNWWWWWMMMWWNWWMMMWWNWWMMMWNWWMMMWWNWMMMMWWWWMMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd,'',;,..','..',,,;;;::ccllooll:;;;;,'''''''....,;;;:;'..';:::cl:;'.',:cldolkNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "NNWWMMWWNNWMMMWWNWWMMWWNNWWMMMWWWWMMMWNNWWMMWWKl,,;;'.',,,'..',,;,;;:::clllc:;,;:;,'...... ...........',,,,;:::;;'..';clolkNWWMMMWNNWMMMWWWWWMMWWWWWMMMWWNWWMMMWWNWWMMWWWW\n" +
                "WWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWW0c,;;'',;;,'...,,,,,;;:::::;,,,,,,,'...................'',,,,,,'',''..';:cl0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "MMMWWWWWMMMWNWWMMMWWNWWMMMWWNWMMMWWWWWMMMWNNWMWWO:,;,,;;;;;...''',,,;;;;;,'.'''''...........'',,;;;;::cccccc:;,''.....';:oKMWWWNWMMMWWWWWMMMWWWWWMMMWNNWMMMWWNWWMMMWWWWMMM\n" +
                "WWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWNk:,,;;;,,,'...'''',,,,,'.........'',,,,,,,;;:::::;:;,,,'..'',,;,......,:xNWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWMMMWNWWMMMWWNWWMMWWWWWWMMWWNWWMMMWWNWWMMWWWNWN0c,;;,,,;,......'',,,..........,,''........,;;;:clccc:;'.  ........'';ckNNWWMMWWNWWMMMWWWWWMMMWWWWMMMWWWWWMMMWWNWWMMWWWW\n" +
                "MWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWNKd:;;;;;,;,.....''''................,;;::cokOxx0K0Okxxl' ...'''''',;;cOWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWW\n" +
                "MMMWWWWWMMMWNWWMMWWWWWMMMWWWWWWMMWWWWWMMMWWWWWMMWWWWN0kdodxkK0;....''','........  ..',;coooxxk00OO0K00Okxo'.',:c:;''',;;lKWWWWWWWWMMWWWWWWMMWWWWMMMWWWWWWMMWWNWWMMWWWWWMMM\n" +
                "WWWWMMWWWWWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWWMWWWWWWWWMWNk,.....',,''..'''.....'',,;;;::::::;;;;;,'...'clllc,'',;;,xWWWWWMWWWWWWWMMWWWWWMMWWWWWWMMWWWWWMMWWWWWWMMMWWW\n" +
                "WWWWMMMWWWWMMMWWWWWMMWWWWWMMMWWWWWWMWWWWWWMMMWWWWMMMWWWWWMMWWWNx'.....',,,'.',;;;,'................';cllc::lddooc,,,,,'cKWWWWWWMWWWWWMMMWWWWWMMWWWWWWMMWWWWWMMWWWWWWMWWWWW\n" +
                "MMMWWWWMMMWWWWWMMMWWWWWWMWWWWWMMMWWWWWMMMWWWWWWMMWWWWMMWWWWWWMMNd.......'''..';;;;;;;;;,,;:ccccloodkkkkxdddddool:,;;,.,OWWWMWWWWWWMMWWWWWMMWWWWWWMMWWWWWWWMWWWWWMMWWWWWWMM\n" +
                "MMWWWWWWMMWWWWWWMWWWWWWMMWWWWWMMMWWWWWMMMWWWWWMMMWWWWWWWWWWWWMWWXo.........'..';;;;;;;;;;;:cloodxxdddddddddooolc;;,,',xNWWWMWWWWWWMMWWWWWMMMWWWWWWMWWWWWMMMWWWWWMMWWWWWMMM\n" +
                "WNWWMMWWWWWWMMWWWWWMMWWNNWMMMMWWWWMMMWWWWMMMWWWWWMMMWWNWWMMMWNWWWNx,..........'',;;;,,,,;,;;:ccclllcclcclllooll:;;,.'dNWWWWWWWMMWWWWWMMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWW\n" +
                "WWWWMMWWWWWWWWWWWWWWMWWWWWWMMWWWWWWWWWWWWWMMWWWWWWMWWWWWWWWWWWWWWWWO;...........'',,,,''''''',,,,,,,,,,,;::cclc:,,''lXWWWWWWWWWMWWWWWWMWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWW\n" +
                "MMMWWWWWMMMWNWWMMMWWWWWMMWWWWWMMMWWWWWMMMWWWWWMMWWNWWMMMWWNWMMMWWNWW0:...........'',,,,'................';ccclc;,''lXWNWWWWMMWWWWMMMWWWWWMMMWWWWWMMMWWWWMMMWWNWWMMWWWNWWMM\n" +
                "WWWWWWWWWMMWWWWWMWWWWWWWWWWWWWWWMWWWWWMWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWKc...........',,;,,,''''....''''',;:cccllc,',lKWWWWWWWWWWWWWWWWWWWWWWMMMWWWWMWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WNWWMMMWWWWMMMWWNWWMMMWWNWMMMWWWWWMMMWWNWWMMWWWWWMMMWWNWWMMWWWWWMMMWWWXx;..........',,,,;;;;;,;;;:::ccccllcclc;';dKWNWMMWWWNWWMMWWNNWMMMWWWWWMMWWWNWWMMWWNWWMMMWWNWWMMWWWW\n" +
                "WWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKd,..........'',,,;;;;;:ccccccccc:c:;,,:kNWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "MMWWWWWWMMMWNWWMMMWWWWWMMWWWWWMMMWWNWWMMWWWWWWMMWWNWWMMMWWNWMMMWWWWWMMMWWNKxc'..........''',,,,;;:;;;;::;;;,',oKWWWMMWWNWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMMWWNWMMM\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0d:................'''''.''..'':kNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "WWWWMMWWWWWMMMWWNWWMMWWNNWMMMWWWWWMMMWWNWWMMMWWWWMMMWWWWWMMWWNWWMMMWWWWWMMWWWWWN0d:'......................:kXWWMMMWNNWMMMWWWWWMMMWWNWMMMWWNWWMMWWWWWMMMWWNWWMMMWWNWWMMWWNW\n" +
                "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKkxo:,'...........';coONWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW\n" +
                "MMWWWWWWMMWWWWWMMMWWWWWMMWWNNWMMMWWWWWMMMWNNWWMMWWNWWMMMWWWWMMMWNNWWMMMWNWWMMMMWWWWMMMWNX0OOOOOOOOOO0KXNWWWMMMWWWWMMMWWNWWMMMWWWWMMMWWWWWMMMWWWWWMMMWNNWMMMWWWWMMMMWWWWMMM\n" +
                "WWWWMMWWWWWWMWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWW\n" +
                "WWWWMMWWWWWMMMWWWWWMMMWWNWWMMWWWWWMMMWWWWWMMWWWWWWMMWWNWWMMWWWWWMMMWWWWWMMWWWWWMMMWWNNWWMMMWWWWMMMWWNWWMMMWWWWWMMWWWWWMMMWWWWWMMWWNNWMMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWW\n" +
                "WMWWWWWWWMWWWWWWMWWWWWWWWWWWWWWMMWWWWWMWWWWWWWMWWWWWWWWWWWWWWMMWWWWWMMWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWMMWWWWWWWWWWWWWWWWWWWWWMMWWWWWWMWWWWWWMWWWWWWWMMWWWWWWWWWWWWWMM\n" +
                "MMMWWWWWMMWWWWWWMMWWWWWMMWWWWWWMMWWWWWMMMWWWWWMMWWNWWMMWWWWWWMMWWWWWMMMWNWWMMMWWWWWMMMMWWWWWMMWWWWWMMMWWNWWMMMWWWWWMMWWNWWMMWWWWWWMMWWWWWMMMWNNWWMMMWWWWMMMWWWWWMMWWWWWWMM\n" +
                "WWWWMMWWWWWWMMWWWWWMMWWWWWWMMWWWWWWMWWWWWWMMWWWWWWMWWWWWWMMWWWWWMMMWWWWWMMWWWWWWMMMWWWWWMMWWWWWWMMWWNWWMMMWWWWWMMWWWWWMMWWWNWWMMWWWWWMMMWWWWWMMWWWWWWMMWWWWWMMMWWWWWMMWWWW\n" +
                "WWWWWMWWWWWMMMWWWWWMMWWWWWWMMWWWWWMMMWWWWWMMWWWWWWMWWWWWWMMWWWWWMMWWWWWWMMWWWWWWMMWWWWWWMMMWWWWWMMWWWWWMMWWWWWWWWWWWWWWMMWWNWWMMWWWWWWMMWWWWWMMWWWWWMMMWWWWWWMWWWWWWMWWWWW\n" +
                "MMWWWWWWMMWWWWWMMMWWWWWMMWWWWWWMMWWWWWMMMWWWWWMMWWNWWMMMWWWWMMMWWNWWMMWWWWWWMMMWNWMMMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWWMMWWWWWMMMWWWWMMWWWWWWMMMWWWWMMMMWWWWMMMWWNWWMMMWWWWMMM\n" +
                "MMMWWWWWWMMWWWWWMMWWWWWWWWWWWWWMWWWWWWWMWWWWWWWWWWWWWMMWWWWWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWWMMWWWWWMMMWWWWWMMWWWWWWMMMWWWWWWWWWWWWMMWWWWWWMMWWWWWMMWWWWWMMMWWWWWMMMWWWWWMM\n" +
                "WWWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWWMMWWWWWWMMMWWWWMMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWMMMWWWWWMMWWWWWWMMWWWW\n" +
                "NWWWMMMWNNWWMMWWWWWMMMWWWWMMMWWNWWMMMWWNWMMMWWWWWMMMWWNWMMMWWNNWMMMWWWWWMMMWNNWMMMWWNNWWMMMWWWWMMMWWWWWMMMWNNWMMMMWNNWMMMWWNWWMMMWWNWMMMWWWWWMMWWNNWMMMWWWWWMMMWNNWMMMMWNW");
    }

    public static void printInfo(Scanner in) {
        System.out.println("You want the truth? You can't handle the truth!");
        String reply = in.nextLine();
        if (reply.equals("I pledge to follow the rules of The Fight Club!")){
            System.out.println("Quote-talking foto-machine, 2019");
            System.out.println("All rights are reserved");
            System.out.println("Do not hesitate to tell your friends about it");
        }
    }

    public static void insertBanknotes(Machine m1, Scanner in) {
        while(true) {
            System.out.println("Where are my money , Lebowski? How much will u give me? [5] [10] [20]. Feel free to [stop] any time!");
            String banknotes = in.nextLine();
            int banknoteValue = 0;

            if (banknotes.equals("stop")){
                break;
            }

            try {
                banknoteValue = Integer.parseInt(banknotes);
                switch (banknoteValue) {
                    case 5:
                        banknoteValue = 5;
                        break;
                    case 10:
                        banknoteValue = 10;
                        break;
                    case 20:
                        banknoteValue = 20;
                        break;
                }
            } catch (Exception e) {
                System.out.println("I don't need all those fakies!");
            } finally {
                if (banknoteValue == 0) {
                    System.out.println("Listen... I've saved you and I'm not going to play out charity! Money!!!");
                } else {
                    m1.acceptPapers(new Banknote(banknoteValue, "BYN"));
                }
            }
        }
    }
}
